{ pkgs, ... }:

{
  imports = [
    ./aspell.nix
    ./atomicparsley.nix
    ./azure-cli.nix
    ./bat.nix
    ./colordiff.nix
    ./dash.nix
    ./delta.nix
    ./exiftool.nix
    ./eza
    ./fd.nix
    ./fdupes.nix
    ./ffmpeg.nix
    ./file.nix
    ./ghq.nix
    ./git
    ./github-cli.nix
    ./gomi.nix
    ./htop.nix
    ./imagemagick.nix
    ./jq.nix
    ./k9s.nix
    ./keychain.nix
    ./kubectl.nix
    ./kubelogin.nix
    ./nkf.nix
    ./peco.nix
    ./pgformatter.nix
    ./ripgrep.nix
    ./ruby.nix
    ./set-docker-detach-keys.nix
    ./shellcheck.nix
    ./skktools.nix
    ./slack.nix
    ./nodePackages.sql-formatter.nix
    ./stern.nix
    ./tmux.nix
    ./trurl.nix
    ./unar.nix
    ./unzip.nix
    ./whichpr.nix
    ./yq.nix
    ./yt-dlp.nix
    ./zsh-history-utils.nix
  ];
}
