#!/bin/sh
# For non-OS X systems, a placeholder for the program from
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

command="reattach-to-user-namespace"

if type $command 2>&1 1>/dev/null; then
  exec $command $@
else
  exec $@
fi
