#!/bin/sh
# For non-OS X systems, a placeholder for the program from
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

command="reattach-to-user-namespace"

if type $command > /dev/null 2>&1; then
  exec $command $@
else
  [ ${1}x = '-lx' ] && shift
  exec $@
fi
