# Based upon: https://qiita.com/yuki-k/items/2a28b40f0bd49b2bcb21

unbind   -T copy-mode Enter
unbind   -T copy-mode y
unbind   -T copy-mode MouseDragEnd1Pane
bind-key -T copy-mode Enter             send -X copy-pipe            "xsel -ip && xsel -op | xsel -ib"
bind-key -T copy-mode y                 send -X copy-pipe            "xsel -ip && xsel -op | xsel -ib"
bind-key -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel "xsel -ip && xsel -op | xsel -ib"

unbind   -T copy-mode-vi Enter
unbind   -T copy-mode-vi y
unbind   -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi Enter             send -X copy-pipe            "xsel -ip && xsel -op | xsel -ib"
bind-key -T copy-mode-vi y                 send -X copy-pipe            "xsel -ip && xsel -op | xsel -ib"
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "xsel -ip && xsel -op | xsel -ib"

unbind  ]
unbind ^]
bind    ] run-shell "xsel -b | tmux load-buffer - && tmux paste-buffer"
bind   ^] run-shell "xsel -b | tmux load-buffer - && tmux paste-buffer"
