#ENC[AES256_GCM,data:Vk4quFvIBeZlv40n,iv:1cMmYUHV8fg8LfXynSDYwc7UnF5xMeBLfCe6mi62nzg=,tag:TPvLFfg+Lcf2CebhmMQgfg==,type:comment]
test_key: ENC[AES256_GCM,data:SHaGLVr4YX7TyA==,iv:qxSn/irNWRxNpMEqXauogF5PNDWalio6m7tuuBepfd0=,tag:RM3O5l9BhCoSyrkwfSm9eQ==,type:str]
sops:
  shamir_threshold: 1
  age:
    - recipient: age1w50n272drug92rym0wgtfpj4js7t5lx4edrvzry9ngeh3gmshsks69l4p3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabCt1eTdva2hvVWxsa3Jk
        NzRTUkJOekxxSXFwaFVHYmZqRWVMVldrV2xzCldQZnlTQ0w4WmVCS2dKMVUzTlVw
        Z09BMC90V0ZYb0U1UTQrYVExcEpaQ2sKLS0tIEJ5WXNOQWk3M0I0aFJQbHpScVRE
        Z3lpZlovVnNCQk41bWhZbkEyOWFmRmMKkrt1Vxc6ro66ve4/2V2XKo/re9al5gB+
        0UL+58c01oqEg4MkzD00j08B21uhwu3aHoXzq7iXHrxrV3rtU3PWHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T14:20:37Z"
  mac: ENC[AES256_GCM,data:26Eig3O9EeHZLruXjouFDIoTBs2HpSVxvrYOA9XqHyZPOkmdWXqN7K2MWI1+pHLC84Amu08krH2/LnWTz2XsNZfX53nMsWOE7R1R0KogldXs2FLnxfyuWsbxLbBZaO1q1MRaqL+GdLvi/L9mk0Rql7Fp58dapuRvZdv1fLysR2c=,iv:tCXA8CUO6xDdDVM+pjeXje7kfvRjBM/biuAz4GM+6Ek=,tag:9sT6Zq1LSm4Jj2PH3mowKg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
