#ENC[AES256_GCM,data:us5mU7xlvl1WVUeS,iv:1cMmYUHV8fg8LfXynSDYwc7UnF5xMeBLfCe6mi62nzg=,tag:kosNa8YUISHM6jLAq5pVFw==,type:comment]
test_key: ENC[AES256_GCM,data:+vb7a4Eo4hVBZA==,iv:qxSn/irNWRxNpMEqXauogF5PNDWalio6m7tuuBepfd0=,tag:LWdZT+LJY5tB6PydC5G0hg==,type:str]
sops:
  lastmodified: "2026-01-28T11:08:09Z"
  mac: ENC[AES256_GCM,data:XF6tfubLRIva9svLQGXRFCPEnB+cjXc14Ct339zfOrR621/pkOI4OnWFLbuft5mudiSQ0hCCtpV/LX1hKpcBKIW9yeHh8CoTKsF3PhQaDMpGLQiuAtzFhG+bqhfqd8Hg41Ou40COpEZ24280sFmjtUR9f0ecDTvUkoyS8ceAuYo=,iv:aZhG02CiG6j/kvuTfZD3MA7arM9IQAXECsRj9CsbR3w=,tag:0EYm1U+tXuLxzRYL0ktd4g==,type:str]
  pgp:
    - created_at: "2026-01-28T11:08:09Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA+niSKbe0PK5AQ//UOT8Q9xYRdHHa1n2c9SbJISgOXOJyRZHF8/cxW6oH9Io
        /aUfYVWpIAtctmU4JBWrVBggXe3aGyGAmcmWx4LtZihxJRiEenAORNawfX/z/KvS
        U9QGr1iRRXNxTN+zMFAzqlcDkqZs1RgxqCF4abaToUvq1Xn/Dy4rXWAH2375Wlut
        lZIl4Fkj3mYPunsqQzF+Zs7KiT09CYlzJESskud52r/EPzEIMHIKf3sHTyQIywTB
        oH8OiVDyf5XtmWWP4ZVtJknqQtu4CxsHhyqzmYLaSe1R17wmNnsCnHL3G5cfdggD
        y/TslaKLvzVjHXnQ2FJigJDEdq54L77Sp0ynKFz72HAn8xdKiRFyPH9QqCQspuei
        wuhqlQVzqtdReRsCBMIN8iPCZQmIh97ZGvGlV0tRtkeXX3vwhzRFr8CNg81hCraY
        hjwaJQD0cqkEzQTBHC52DONxSfanNJxS4fgXk4EgCMCnLmoIZIoFvIveUyFBtdJn
        xBf1AOeecXUFAWU3wWj+WNa9Nfv0JM2qWWpqv2wPVY5R2NSmUhaVO+AxcFnPnjRv
        tGZsgXP6uh3zkNYyH8WqI1XBYTacVZT5HU/QBLm0UYXoFlfybjD0dHikHcn3KbV5
        uZin4ibMOlHGpCPv9OpIfOUz1LWwRzP5lC+gvXa0/B1fOCqOSdv21Qrq6+Zr817S
        XgESkd+XUoCpQwqDM7zwTPWWgrmfzA8Tt7mL8JCOqI62lz+2HgkNQyjM2budBsVD
        nxGOZnflsuWV+WlrMe34r6L+Esh6XDfXNh2bbXuWrL/CYQnjgoIb8fZhawqcwEU=
        =i/Pt
        -----END PGP MESSAGE-----
      fp: 7B152038A70467A43B266AEE0967B4FC0A2D3E0E
  unencrypted_suffix: _unencrypted
  version: 3.11.0
